language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kasramp-github"
    token:
        secure: "FgraG59k/JZyxktvCCtUAGZpFxXrVCPCJlGGMuFAmtOQ29WDR+QRSv75D853B6n3emkA9xiqig0bDcX946M0SRt4X8B5G0cwsOU09JsQDVBfkOMX/1JA9sC90JdrDdmqNsoCNYMmtAJNR3wQtGX6uRt5lPkrHe6B47g4ly6qnnjF9xaUfs0yAYeQfLzq0l0PHNu7e2GS1RRuaNFFBbMBDBL/drQc6JUW9uGPYhFB4n3D5I6ZVHvQNVGpdypn67AmZuSaL1G4cwYeqj2d2aUmWTtb+CrReIFbI37oZ3qja10hSvnMKrq/4QIxvxcs5gT9/iiHXqgsAVKbf0DVfnUMUiU5fDMhlihjdrVki9IfvCgY5Ftj1WdNZOK+Y3zRwY1xU7UNh/fTmLHpzwWubu0Mi+fvXtqox2TcXbQoXYizgiednHzu/BAxk0DpDnjf4Q0BqlPmLw1AWzY4Icd2TMAVn4Ja9gUUVlsPJGsZ3kIZEUx/iE/xIbjnPC9fEHrEdApR3SSJiA0o8e3xPlfEpDp06o+Z9kOKNO4lAstUPFOupOOHTuOXsU2BhAT/WgQ3ADwDZQ0wrGpVRY7sM2FI0riB73S6n4QWBdqb/9YWmNeMBcP2aLXHgdfGOECDSNBLh2NSp+a1Q17cmfEiE4tXJYgiw/+hX6jFkEPDIEPss7aUHZs="
    branches:
      - develop

jdk:
- oraclejdk10
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
