language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kasramp-github"
    token:
      secure: "sSV2kzvGiVzb/9dKwEAnKTn7hgBh47PoY2j8hoZMnwPhfI8zfcw60fsJkUQ9ohjI4jPJddhyb73JxR/212Zt2yK/D97y23z4TVURhyzOzArfxLWjzpJiGoZ6O6onu2Ymad2T4LyUiv5dE0U0t2vvnO+BV2rbHkcFSjp30O2OkU3ef5qk86GXPePJdwJvjU94PtTVU1ozMIQC9p8DVuuuOr4dinjJ3hQBBncf3sIQEg6dOBHjW2S/4vhtWto2g+3g75PugOx9eocSzH4pVDyOwafB8DWLnvgrbH9Zj3EaGI7Zp3nsyw2BIszMRsXEA1yt+CrGJHWFc1LbvQJnaO6MAC8OzgbnFsK9chExOi600VT7pHnPUFL9By5M+BFuCT2kaanr/dk1rPoBuaiCSxKpPq4TuZr7xg0GLOSImWTs5Bf4vANTp++wjLrdi6ppsI50nd1oo3f2WMwEeyZEUZ9tOe8TBWUqeDJ8Y/VQzIM4yGvexT+qHvuB/8gC2KzrTswjrytn1Y5nP7zqjBZLcOvKsAOhesNuwVGjX/+bvc5BZQJSIPcZyaJdOY6By2sPUHwR025oIMWosQfrssaMN/QOhtwqTYgUMIUp1YLUmoxKo+6MNnSdzPHJTq7znn3+I0O1EcDt8nfnVTAaSGrNKMJxXxn4NkjOr7CRP4z9hxNgQFk="
    branches:
      - develop

jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
    secure: "sSV2kzvGiVzb/9dKwEAnKTn7hgBh47PoY2j8hoZMnwPhfI8zfcw60fsJkUQ9ohjI4jPJddhyb73JxR/212Zt2yK/D97y23z4TVURhyzOzArfxLWjzpJiGoZ6O6onu2Ymad2T4LyUiv5dE0U0t2vvnO+BV2rbHkcFSjp30O2OkU3ef5qk86GXPePJdwJvjU94PtTVU1ozMIQC9p8DVuuuOr4dinjJ3hQBBncf3sIQEg6dOBHjW2S/4vhtWto2g+3g75PugOx9eocSzH4pVDyOwafB8DWLnvgrbH9Zj3EaGI7Zp3nsyw2BIszMRsXEA1yt+CrGJHWFc1LbvQJnaO6MAC8OzgbnFsK9chExOi600VT7pHnPUFL9By5M+BFuCT2kaanr/dk1rPoBuaiCSxKpPq4TuZr7xg0GLOSImWTs5Bf4vANTp++wjLrdi6ppsI50nd1oo3f2WMwEeyZEUZ9tOe8TBWUqeDJ8Y/VQzIM4yGvexT+qHvuB/8gC2KzrTswjrytn1Y5nP7zqjBZLcOvKsAOhesNuwVGjX/+bvc5BZQJSIPcZyaJdOY6By2sPUHwR025oIMWosQfrssaMN/QOhtwqTYgUMIUp1YLUmoxKo+6MNnSdzPHJTq7znn3+I0O1EcDt8nfnVTAaSGrNKMJxXxn4NkjOr7CRP4z9hxNgQFk="
