version: '3.8'
services:
  consul-dev:
    image: consul:1.15.4
    container_name: consul-dev
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul-server-config.json:/consul/config/consul-config.json
      - ./consul-data:/consul/config
    #command: "agent -dev -client 0.0.0.0"