spring.application.name=Eris
#spring.resources.add-mappings=false
management.endpoints.web.exposure.include=*
management.endpoint.heapdump.access=unrestricted
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.enabled=false

# MCP server configs
logging.level.org.springframework.ai.mcp=INFO
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY:}
spring.ai.mcp.server.name=eris-weather-mcp-server
spring.ai.mcp.server.version=v1.0
spring.ai.mcp.server.type=SYNC