name: Build and Release
on:
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-${{ github.ref_name }}-sonar
          restore-keys: ${{ runner.os }}-${{ github.ref_name }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kasramp-github -Dsonar.projectKey=Eris
      - uses: actions/checkout@v3
      - name: Set last commit
        shell: bash
        run: |
          echo "::set-output name=LAST_COMMIT::$(git log -n 1)"
        id: version
      - name: Get previous tagged version
        id: previous_tagged_version
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash
        run: |
          echo "::set-output name=OLD_TAGGED_VERSION::$(git for-each-ref --sort=-creatordate --format='%(refname:short)' refs/tags --count 10 | grep -oP '^eris-(\d+).*' | head -1)"
      - name: Tag
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.LAST_COMMIT }}
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd ${GITHUB_WORKSPACE}
          chmod +x "${GITHUB_WORKSPACE}/util/release.sh"
          ./${GIHUB_WORKSPACE}/util/release.sh
      - name: Get latest tagged version
        id: tagged_version
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash
        run: |
          echo "::set-output name=TAGGED_VERSION::$(git for-each-ref --sort=-creatordate --format='%(refname:short)' refs/tags --count 10 | grep -oP '^eris-(\d+).*' | head -1)"
      - name: Generate release note
        uses: mikepenz/release-changelog-builder-action@v3.7.1
        id: release_note
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "kasramp"
          config-name: ".github/release.json"
          fromTag: ${{ steps.previous_tagged_version.outputs.OLD_TAGGED_VERSION }}
          toTag: ${{ steps.tagged_version.outputs.TAGGED_VERSION }}
      - name: Perform release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          tag_name: ${{ steps.tagged_version.outputs.TAGGED_VERSION }}
          body: ${{ steps.release_note.outputs.changelog }}
          files: |
            target/*.jar
