name: Build and Release
on:
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-${{ github.ref_name }}-sonar
          restore-keys: ${{ runner.os }}-${{ github.ref_name }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kasramp-github -Dsonar.projectKey=Eris
      - uses: actions/checkout@v3
      - name: Set last commit
        shell: bash
        run: |
          echo "LAST_COMMIT<<EOF" >> $GITHUB_OUTPUT
          echo "$(git log -n 1)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: version
      - name: Tag
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.LAST_COMMIT }}
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd ${GITHUB_WORKSPACE}
          chmod +x "${GITHUB_WORKSPACE}/util/release.sh"
          ./${GIHUB_WORKSPACE}/util/release.sh
      - name: Get latest tagged version
        id: tagged_version
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash
        run: |
          echo "TAGGED_VERSION=$(git for-each-ref --sort=-creatordate --format='%(refname:short)' refs/tags --count 10 | grep -oP '^eris-(\d+).*' | head -1)" >> $GITHUB_OUTPUT
      - name: Perform release
        uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          tag: ${{ steps.tagged_version.outputs.TAGGED_VERSION }}
          generateReleaseNotes: true
          artifacts: "target/*.jar"