name: Generate Release Note
on:
  release:
    types: [published]
jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Release Note
        uses: release-drafter/release-drafter@v5.23.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/release.yml