name: Do release
on:
  workflow_run:
    workflows: ["Build and Tag"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Make release directory
        run: mkdir release_files
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_and_tag.yml
          workflow_conclusion: success
          branch: master
          path: release_files/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_files/master-jar/*.jar
