name: Do release
on:
  workflow_run:
    workflows: ["Build and Tag"]
    branches: [master]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: master-jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.jar