name: CI/CD pipeline

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORG} -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      - uses: actions/checkout@v2
      - name: Set last commit
        shell: bash
        run: |
          echo "::set-output name=LAST_COMMIT::$(git log -n 1)"
        id: version
      - name: Release
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.LAST_COMMIT }}
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd ${GITHUB_WORKSPACE}
          chmod +x "${GITHUB_WORKSPACE}/util/release.sh"
          ./${GIHUB_WORKSPACE}/util/release.sh
